### ISSUE TITLE
NPE when running V3.3.0 on spigot 1.11.2

### ISSUE THREAD

**Issue by Volander** [ExtendedAlpha/Wiki#1]
[05:16:06] [Server thread/INFO]: [SeparateWorldItems] Enabling SeparateWorldItems v3.3.0
[05:16:06] [Server thread/INFO]: ----------------------------
[05:16:06] [Server thread/INFO]:  SeparateWorldItems Updater
[05:16:06] [Server thread/INFO]:  
[05:16:06] [Server thread/INFO]: You are running 3.3.0
[05:16:06] [Server thread/INFO]: The latest version
[05:16:06] [Server thread/INFO]: of SeparateWorldItems!
[05:16:06] [Server thread/INFO]:  
[05:16:06] [Server thread/INFO]: ----------------------------
[05:16:06] [Server thread/ERROR]: Error occurred while enabling SeparateWorldItems v3.3.0 (Is it up to date?)
java.lang.NullPointerException
	at com.github.authme.configme.knownproperties.ConfigurationDataBuilder.lambda$collectData$1(ConfigurationDataBuilder.java:45) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_111]
	at com.github.authme.configme.knownproperties.ConfigurationDataBuilder.collectData(ConfigurationDataBuilder.java:45) ~[?:?]
	at com.github.authme.configme.SettingsManager.<init>(SettingsManager.java:47) ~[?:?]
	at org.extendedalpha.separateworlditems.config.Settings.<init>(Settings.java:37) ~[?:?]
	at org.extendedalpha.separateworlditems.SeparateWorldItems.initSettings(SeparateWorldItems.java:331) ~[?:?]
	at org.extendedalpha.separateworlditems.SeparateWorldItems.onEnable(SeparateWorldItems.java:129) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:375) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:325) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:419) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:380) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:335) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

**Comment by Jaryn-R** [comment]
Ok so I already know how to fix this issue, but I'm not currently at my computer so I'll push the fix later tonight. Sorry for the inconvenience, if you want everything working, just downgrade to v3.2.0

**Comment by Jaryn-R** [comment]
Fixed in 2974585d22260cca265119b2256f110176ac63b1
